### ISSUE TITLE
Escaping does not work in string literals

### ISSUE THREAD

**Issue by ChrisCA** [jonahlund/vy#1]
```
use vy::{lazy, Render};

fn main() {
    let test1 = lazy!(<test>{"hello <you>"}</test>);
    let test2 = lazy!(<test>"hello <you>"</test>);

    print!("{}", test1.render());
    print!("{}", test2.render());
}
```

Output:
`<test>hello &lt;you&gt;</test><test>hello <you></test>`

I guess it's not supposed to be like that. Is it?

Best regards
Christian

**Comment by jonahlund** [comment]
Hi, You are absolutely correct the non braced literals should also be escaped.

Thanks
