### ISSUE TITLE
Compile time markdown rendering

### ISSUE THREAD

**Issue by imbolc** [jonahlund/vy#4]
For long text blocks, it would be convenient to write them in Markdown with compile-time rendering. This would, in turn, reduce the need to quote strings.

**Comment by jonahlund** [comment]
This is out of scope for this crate, but can be implemented rather trivially by making a proc macro that proxies the tokens through something like [comrak](https://github.com/kivikakk/comrak) or [markdown-rs](https://github.com/wooorm/markdown-rs).
